services:
  - type: web
    name: tripifi-cgr
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm ci && npx --no-install next build
    startCommand: npx --no-install next start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
